Repository VROOM-Project/vroom-express, pull requests merged in 2020-03, with the labels that each got.

#37 Handle shipments
  src/config.js
  src/index.js
Labels: feature request

#39 introduce config.yml in root which has to be explicitly created
  .gitignore
  CHANGELOG.md
  README.md
  config.yml
  package.json
  src/config.js
  src/index.js
Labels: enhancement

#40 Last fixes for v0.5.0
  CHANGELOG.md
  src/index.js
Labels: bug
